USE SECOND_WEEK
--TO DISPLAY ALL DATA FROM TABLE ACCOUNT
SELECT * FROM ACCOUNT
--TO DISPLAY ONLY COLUMNS ACCOUNT_ID AND AVAILABLE BALANCE  FROM THE TABLE
SELECT ACCOUNT_ID, AVAIL_BALANCE FROM ACCOUNT

SELECT CUST_ID, AVAIL_BALANCE, OPEN_DATE FROM ACCOUNT

--TO DISPLAY ONLY DISTINCT VALUES FROM A COLUMN OPEN_BRANCH
SELECT DISTINCT OPEN_BRANCH_ID FROM ACCOUNT

--TO DISPLAY ONLY CERTAIN NUMBER OF ROWS/LINES IN A TABLE
--IF REQUIRED TO SEE A TABLE WITHOUT OVERLOADING THE SYSTEM
SELECT TOP 10 * FROM ACCOUNT

--DISPLAYS ALL ROWS WITH PRODUCT_CD IS MM AND BRANCH ID IS 1
SELECT * FROM ACCOUNT
WHERE PRODUCT_CD = 'MM' AND OPEN_BRANCH_ID = 1

--DISPLAYS AVAIL_BALANCE, OPEN_BRANCH_ID, PRODUCT_CD COLUMNS
--FOR ROWS WITH PRODUCT_CD IS MM AND BRANCH ID IS 1 AND AVAIL_BALANCE > 9000
SELECT AVAIL_BALANCE, OPEN_BRANCH_ID, PRODUCT_CD FROM ACCOUNT
WHERE PRODUCT_CD = 'MM' AND OPEN_BRANCH_ID = 1 AND AVAIL_BALANCE > 9000

-- DIPSLAYS ROWS WITH ANY OF THOSE CONDITIONS IS TRUE:  PRODUCT_CD IS MM OR BRANCH ID IS 1 OR AVAIL_BALANCE > 9000
SELECT * FROM ACCOUNT
WHERE PRODUCT_CD = 'MM' OR OPEN_BRANCH_ID = 1 OR AVAIL_BALANCE > 9000

--ALL EXCEPT FOR OPEN_BRANCH_ID = 1 AND  AVAIL_BALANCE>1000
SELECT AVAIL_BALANCE, CUST_ID, OPEN_BRANCH_ID FROM ACCOUNT
WHERE NOT OPEN_BRANCH_ID = 1 AND AVAIL_BALANCE>=1000
-- WHERE OPEN_BRANCH_ID != 1

--DISPLAYS WHERE AVAL_BALANCE IS ENTERED(NOT NULL)
SELECT * FROM ACCOUNT WHERE AVAIL_BALANCE IS NOT NULL
BEGIN TRAN ONE_ONE
UPDATE ACCOUNT
SET CLOSE_DATE = '2004-11-14 00:00:00.000'
WHERE ACCOUNT_ID =22
ROLLBACK TRAN ONE_ONE

-- ROWS WITH DISTINCT PRODUCT_CD THAT STARTS WITH C 
SELECT DISTINCT PRODUCT_CD
FROM ACCOUNT
WHERE PRODUCT_CD LIKE 'C%' 

SELECT * FROM ACCOUNT
WHERE PRODUCT_CD LIKE '[CM]%'

SELECT * FROM EMPLOYEE

SELECT * FROM EMPLOYEE
WHERE TITLE LIKE '%MANAGER%'

--DISPLAYS MINIMUM VALUE 
SELECT MIN(AVAIL_BALANCE) FROM ACCOUNT
WHERE PRODUCT_CD = 'MM'

--DISPLAYS NUMBER OF ROWS WHERE PRODUCT_CD = 'MM'
SELECT COUNT(ACCOUNT_ID) FROM ACCOUNT
WHERE PRODUCT_CD = 'MM'

--SUMS ALL VALUES OF AVAIL_BALANCE WHOSE PRODUCT_CD = 'CHK'
SELECT SUM(AVAIL_BALANCE) FROM ACCOUNT
WHERE PRODUCT_CD = 'CHK'

--AVERAGE OF AVAIL_BALANCE FOR ALL ROWS
SELECT AVG(AVAIL_BALANCE) FROM ACCOUNT